core:
  logging:
    level: INFO
dse:
  cluster_name: "cluster"
  datastax_version: "6.8.36"
  repository_name: "python"
  config_profile_name: "python"
  opscenter_username: "admin"
  opscenter_password: "opscenter"
  opscenter_server_ip: "10.1.1.1"
  install_credential_name: "python"
  install_credential_username: "ubuntu"
  install_credential_key: "SAMPLE KEY"
  cassandra_default_password: "cassandra"

cluster:
  datacenters:
    - name: "dc1"
      solr_enabled: false
      spark_enabled: false
      graph_enabled: false
      hadoop_enabled: false
    - name: "dc2"
      solr_enabled: true
      spark_enabled: false
      graph_enabled: false
      hadoop_enabled: false